# Generated by Django 4.1.7 on 2023-04-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='productattributekey',
            options={'verbose_name': 'ProductAttributeKey'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'ProductAttributeValue'},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'verbose_name': 'ProductBrand'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'ProductCategory'},
        ),
        migrations.AlterModelOptions(
            name='productrelatedattribute',
            options={'verbose_name': 'ProductRelatedAttribute'},
        ),
        migrations.AlterModelOptions(
            name='productspecs',
            options={'verbose_name': 'ProductSpecs'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='code',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='分类代码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='父级Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='founder',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建者[username in the User table]'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.FloatField(default=0, verbose_name='重量[保留两位小数点]'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_no',
            field=models.CharField(db_index=True, max_length=48, verbose_name='货号'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_editor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人[username in the User table]'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64, verbose_name='主名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.FloatField(default=0, verbose_name='净重[保留两位小数点]'),
        ),
        migrations.AlterField(
            model_name='product',
            name='place_of_origin',
            field=models.CharField(max_length=32, verbose_name='产地'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productbrand', verbose_name='商品品牌'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spu_number',
            field=models.CharField(max_length=48, verbose_name='商品编号'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_name',
            field=models.CharField(max_length=64, verbose_name='副名称'),
        ),
        migrations.AlterField(
            model_name='productattributekey',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcategory', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='productattributekey',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='属性key代码'),
        ),
        migrations.AlterField(
            model_name='productattributekey',
            name='founder',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建者[username in the User table]'),
        ),
        migrations.AlterField(
            model_name='productattributekey',
            name='last_editor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人[username in the User table]'),
        ),
        migrations.AlterField(
            model_name='productattributekey',
            name='name',
            field=models.CharField(max_length=32, verbose_name='属性名称'),
        ),
        migrations.AlterField(
            model_name='productattributekey',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='优先权'),
        ),
        migrations.AlterField(
            model_name='productattributekey',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Unavailable'), (2, 'Deleted')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='attr_value',
            field=models.CharField(max_length=48, verbose_name='属性值'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='attribute_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productattributekey', verbose_name='属性key'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='founder',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建者[username in the User table]'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='last_editor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人[username in the User table]'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='优先权'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Unavailable'), (2, 'Deleted')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_code',
            field=models.CharField(max_length=32, unique=True, verbose_name='属性值代码'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='en_name',
            field=models.CharField(max_length=48, verbose_name='英文品牌'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='founder',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建者[username in the User table]'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='info',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='品牌信息'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='last_editor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人[username in the User table]'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='logo',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='品牌LOGO URL'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='商品品牌'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='优先权'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='status',
            field=models.IntegerField(choices=[(0, 'Init'), (1, 'Draft'), (2, 'Online'), (3, 'Deleted')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='en_name',
            field=models.CharField(max_length=128, verbose_name='英文分类名'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='founder',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建者[username in the User table]'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='last_editor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人[username in the User table]'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=64, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='优先权'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='status',
            field=models.IntegerField(choices=[(0, 'Init'), (1, 'Draft'), (2, 'Online'), (3, 'Deleted')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='productrelatedattribute',
            name='founder',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建者[username in the User table]'),
        ),
        migrations.AlterField(
            model_name='productrelatedattribute',
            name='last_editor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人[username in the User table]'),
        ),
        migrations.AlterField(
            model_name='productrelatedattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='productrelatedattribute',
            name='product_attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productattributevalue', verbose_name='商品属性'),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='founder',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='创建者[username in the User table]'),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='last_editor',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='最后修改人[username in the User table]'),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='优先权'),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='sku',
            field=models.CharField(db_index=True, max_length=24, unique=True, verbose_name='商品SKU'),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='sku_name',
            field=models.CharField(max_length=32, verbose_name='SKU值'),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Unavailable'), (2, 'Deleted')], default=0, verbose_name='状态'),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'code')},
        ),
    ]
