# Generated by Django 4.1.7 on 2023-05-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productbrand_json_object_productbrand_version_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
