# Generated by Django 4.1.7 on 2023-05-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='json_object',
            field=models.JSONField(blank=True, null=True, verbose_name='旧版本数据'),
        ),
    ]
