# Generated by Django 4.1.7 on 2023-05-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productbrand_json_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbrand',
            name='name',
            field=models.CharField(max_length=32, verbose_name='商品品牌'),
        ),
    ]
