# Generated by Django 4.1.7 on 2023-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productbrand_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattributekey',
            options={'ordering': ('priority', '-id'), 'verbose_name': 'ProductAttributeKey'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'ordering': ('priority', '-id'), 'verbose_name': 'ProductAttributeValue'},
        ),
        migrations.AddField(
            model_name='productspecs',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='价格'),
            preserve_default=False,
        ),
    ]
