# Generated by Django 4.1.7 on 2023-05-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productspecs_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='优先权'),
        ),
    ]
