# Generated by Django 4.1.7 on 2023-05-16 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(max_length=128, verbose_name='图片地址')),
                ('priority', models.IntegerField(default=0, verbose_name='优先权')),
                ('is_main', models.BooleanField(default=False, verbose_name='是否是主图')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='商品')),
            ],
            options={
                'db_table': 'product_image',
                'ordering': ('priority', '-id'),
            },
        ),
    ]
