# Generated by Django 4.1.7 on 2023-04-03 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
                ('nickname', models.CharField(db_index=True, help_text='用户昵称', max_length=64, unique=True)),
                ('phone', models.CharField(blank=True, help_text='联系电话', max_length=24, null=True)),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女'), (3, '保密')], default=0, help_text='性别')),
                ('user', models.OneToOneField(help_text='会员', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_member',
            },
        ),
    ]
