# Generated by Django 4.1.7 on 2023-04-22 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_chinaprovincearea'),
        ('member', '0002_alter_usermember_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
                ('zip_code', models.CharField(blank=True, help_text='邮编', max_length=12, null=True)),
                ('name', models.CharField(help_text='姓名', max_length=64)),
                ('phone', models.CharField(help_text='联系电话号码', max_length=16)),
                ('province', models.CharField(blank=True, help_text='省份', max_length=36, null=True)),
                ('city', models.CharField(blank=True, help_text='城市', max_length=36, null=True)),
                ('district', models.CharField(blank=True, help_text='区', max_length=48, null=True)),
                ('street', models.CharField(help_text='街道', max_length=128)),
                ('note', models.CharField(help_text='地址备注', max_length=36)),
                ('is_in_the_book', models.BooleanField(default=False, help_text='是否显示在地址簿中')),
                ('is_delete', models.BooleanField(default=False, help_text='是否已经删除')),
                ('country', models.ForeignKey(help_text='国家', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.country')),
                ('user_member', models.ForeignKey(help_text='会员', null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.usermember')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
