# Generated by Django 4.1.7 on 2023-04-27 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_chinaprovincearea_parent_code'),
        ('member', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, help_text='省份', max_length=36, null=True)),
                ('city', models.CharField(blank=True, help_text='城市', max_length=36, null=True)),
                ('district', models.CharField(blank=True, help_text='区', max_length=48, null=True)),
                ('street', models.CharField(help_text='街道', max_length=128)),
            ],
            options={
                'db_table': 'china_address',
            },
        ),
        migrations.CreateModel(
            name='ChinaAddressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, help_text='省份', max_length=36, null=True)),
                ('city', models.CharField(blank=True, help_text='城市', max_length=36, null=True)),
                ('district', models.CharField(blank=True, help_text='区', max_length=48, null=True)),
                ('street', models.CharField(help_text='街道', max_length=128)),
            ],
            options={
                'db_table': 'china_address_snapshot',
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='district',
        ),
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.CreateModel(
            name='AddressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
                ('zip_code', models.CharField(blank=True, help_text='邮编', max_length=12, null=True)),
                ('name', models.CharField(help_text='姓名', max_length=64)),
                ('phone', models.CharField(help_text='联系电话号码', max_length=16)),
                ('note', models.CharField(help_text='地址备注', max_length=36)),
                ('is_delete', models.BooleanField(default=False, help_text='是否已经删除')),
                ('china_address_snapshot', models.ForeignKey(help_text='中国地址', on_delete=django.db.models.deletion.CASCADE, to='member.chinaaddresssnapshot')),
                ('country', models.ForeignKey(help_text='国家', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.country')),
                ('user_member', models.ForeignKey(help_text='会员', null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.usermember')),
            ],
            options={
                'db_table': 'address_snapshot',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='china_address',
            field=models.ForeignKey(default='', help_text='中国地址', on_delete=django.db.models.deletion.CASCADE, to='member.chinaaddress'),
            preserve_default=False,
        ),
    ]
