# Generated by Django 4.1.7 on 2023-04-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_chinaaddress_chinaaddresssnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='address',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最新一次更新'),
        ),
        migrations.AlterField(
            model_name='addresssnapshot',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='addresssnapshot',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最新一次更新'),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最新一次更新'),
        ),
    ]
