# Generated by Django 4.1.7 on 2023-05-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_address_create_at_alter_address_last_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Man'), (2, 'Woman'), (3, 'Secret')], default=0, help_text='性别'),
        ),
    ]
