# Generated by Django 4.1.7 on 2023-04-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
                ('celery_task_id', models.CharField(db_index=True, help_text='后台下载任务id', max_length=32)),
                ('file_path', models.CharField(help_text='文件保存路径', max_length=128)),
                ('status', models.IntegerField(choices=[[0, 'INIT'], [1, 'PENNING'], [2, 'FAILED'], [3, 'SUCCESS']], help_text='状态')),
                ('operator', models.CharField(help_text='操作人username', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
