# Generated by Django 4.1.7 on 2023-04-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerdownload',
            name='status',
            field=models.IntegerField(choices=[[0, 'INIT'], [1, 'PENNING'], [2, 'FAILED'], [3, 'SUCCESS']], default=0, help_text='状态'),
        ),
    ]
