# Generated by Django 4.1.7 on 2023-04-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_managerdownload_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
                ('name', models.CharField(help_text='名称', max_length=36, unique=True)),
                ('file_src', models.CharField(help_text='文件路径', max_length=128)),
                ('index', models.IntegerField(default=0, help_text='排序')),
                ('link_url', models.CharField(blank=True, help_text='链接URL', max_length=128, null=True)),
            ],
            options={
                'db_table': 'banner',
            },
        ),
    ]
