# Generated by Django 4.1.7 on 2023-04-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
                ('gec_code', models.CharField(help_text='GEC代码', max_length=4, unique=True)),
                ('name', models.CharField(help_text='名称', max_length=48)),
            ],
            options={
                'db_table': 'country',
            },
        ),
    ]
