# Generated by Django 4.1.7 on 2023-04-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaProvinceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(help_text='行政区域代码', max_length=12)),
                ('name', models.CharField(help_text='名称', max_length=48)),
            ],
            options={
                'db_table': 'china_province_area',
                'unique_together': {('area_code', 'name')},
            },
        ),
    ]
