# Generated by Django 4.1.7 on 2023-04-29 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0002_alter_manageruser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageruser',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='manageruser',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='最新一次更新'),
        ),
        migrations.AlterField(
            model_name='manageruser',
            name='nickname',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='manageruser',
            name='phone',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='manageruser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='会员'),
        ),
    ]
