# Generated by Django 4.1.7 on 2023-05-06 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0003_alter_manageruser_create_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField(choices=[(0, 'Client'), (1, 'Management')], default=0, verbose_name='登录端')),
                ('ip_address', models.CharField(max_length=16, verbose_name='IP地址')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='登录地区')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='会员')),
            ],
            options={
                'db_table': 'user_login_log',
            },
        ),
    ]
