# Generated by Django 4.1.7 on 2023-05-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_userloginlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginlog',
            name='ip_address',
            field=models.CharField(db_index=True, max_length=16, verbose_name='IP地址'),
        ),
    ]
