# Generated by Django 4.1.7 on 2023-05-25 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_manageruser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='最新一次更新')),
                ('founder', models.CharField(blank=True, help_text='username in the User table', max_length=150, null=True, verbose_name='创建者')),
                ('last_editor', models.CharField(blank=True, help_text='username in the User table', max_length=150, null=True, verbose_name='最后修改人')),
                ('code', models.CharField(max_length=32, verbose_name='网点代码')),
                ('name', models.CharField(max_length=64, verbose_name='网点名称')),
                ('manager', models.CharField(max_length=150, verbose_name='负责人')),
                ('classify', models.IntegerField(choices=[(0, 'Self Operated'), (1, 'Proxy'), (2, 'Franchisee')], default=0, verbose_name='网点类型')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='网点地址')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='网点联系方式')),
                ('location', models.CharField(blank=True, max_length=128, null=True, verbose_name='地图地址')),
                ('business_hours', models.CharField(max_length=48, verbose_name='营业时间')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='网点介绍')),
                ('sequence', models.IntegerField(default=0, verbose_name='排序[数字越大越靠前]')),
            ],
            options={
                'db_table': 'web_site',
                'ordering': ('sequence', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ManagerWebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.manageruser', verbose_name='管理员')),
                ('web_site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.website', verbose_name='网点')),
            ],
            options={
                'db_table': 'manager_web_site',
            },
        ),
    ]
